management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, info, metrics, httpexchanges

spring:
  application:
    name: SafetyNet Alerts Backend