spring:
  application:
    name: SafetyNet Alerts Backend
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, info, metrics, httpexchanges
logging:
  level:
    root: INFO
  file:
    name:  ./safetynet-alert-backend-logs.log